# Generated by Django 4.2.7 on 2024-01-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainTestApp', '0003_alter_gamedata_blockchain_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='game_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
